import { useState } from 'react'
import Button from '../../components/common/Button.jsx'
import EmptyState from '../../components/common/EmptyState.jsx'
import SectionHeading from '../../components/common/SectionHeading.jsx'
import StatCard from '../../components/dashboard/StatCard.jsx'
import StatusBadge from '../../components/common/StatusBadge.jsx'
import { getAdminSession, getClaims, getItems, getRecoveryPasses, reviewClaim, startRecovery, updateItem } from '../../utils/storage.js'

const statuses = ['Searching', 'Found', 'Claim Pending', 'Recovered', 'Closed']
function ReportsTable({ items, onStatusChange }) { return <div className="overflow-x-auto rounded-2xl border border-ink/10 bg-white"><table className="min-w-[760px] w-full text-left text-sm"><thead className="border-b border-ink/10 bg-paper text-xs uppercase tracking-wider text-ink-muted"><tr>{['Item', 'Type', 'Category', 'Location', 'Date', 'Status', 'Action'].map((head) => <th key={head} className="px-4 py-3 font-bold">{head}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-b border-ink/5 last:border-0"><td className="px-4 py-4 font-bold text-ink">{item.title}</td><td className="px-4 py-4 text-ink-muted">{item.type}</td><td className="px-4 py-4 text-ink-muted">{item.category}</td><td className="px-4 py-4 text-ink-muted">{item.location}</td><td className="px-4 py-4 text-ink-muted">{item.date}</td><td className="px-4 py-4"><StatusBadge status={item.status} /></td><td className="px-4 py-4"><select value={item.status} onChange={(event) => onStatusChange(item.id, event.target.value)} className="rounded-lg border border-ink/15 bg-white px-2 py-1.5 text-xs font-semibold text-ink outline-none focus:border-teal">{statuses.map((status) => <option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div> }
export function AdminDashboardPage() { const [items, setItems] = useState(() => getItems()); const claims = getClaims(); const changeStatus = (id, status) => setItems((current) => current.map((item) => item.id === id ? updateItem(id, { status }) : item)); const stats = [['Total Reports', items.length, 'navy'], ['Lost Items', items.filter((item) => item.type === 'Lost').length, 'teal'], ['Found Items', items.filter((item) => item.type === 'Found').length, 'amber'], ['Potential Matches', Math.max(1, items.filter((item) => item.category === 'Wallets').length), 'teal'], ['Pending Claims', claims.filter((claim) => claim.status === 'Claim Pending').length, 'amber'], ['Recovered Items', items.filter((item) => item.status === 'Recovered').length, 'navy']]; return <><SectionHeading eyebrow="Demo administration" title="Recovery control center" description="Review community reports and keep the recovery process moving." /><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{stats.map(([label, value, accent]) => <StatCard key={label} label={label} value={value} accent={accent} />)}</div><h2 className="mt-10 text-xl font-extrabold text-ink">Reports</h2><div className="mt-4"><ReportsTable items={items} onStatusChange={changeStatus} /></div></> }
export function AdminReportsPage() { const [items, setItems] = useState(() => getItems()); const [query, setQuery] = useState(''); const filtered = items.filter((item) => `${item.title} ${item.location}`.toLowerCase().includes(query.toLowerCase())); const changeStatus = (id, status) => setItems((current) => current.map((item) => item.id === id ? updateItem(id, { status }) : item)); return <><SectionHeading eyebrow="Administration" title="Reports" description="Search and update the status of every report." /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search reports" className="mt-6 w-full max-w-sm rounded-xl border border-ink/15 bg-white px-4 py-3 text-sm outline-none focus:border-teal" /><div className="mt-5"><ReportsTable items={filtered} onStatusChange={changeStatus} /></div></> }
export function AdminClaimsPage() {
  const [claims, setClaims] = useState(() => getClaims())
  const items = getItems()
  const admin = getAdminSession()

  function review(claimId, decision) {
    reviewClaim(claimId, decision, admin)
    setClaims(getClaims())
  }

  return <><SectionHeading eyebrow="Administration" title="Claims" description="Review submitted ownership claims without viewing private item details." /><div className="mt-6 grid gap-4">{claims.length ? claims.map((claim) => {
    const item = items.find((entry) => entry.id === claim.itemId)
    const isFinal = ['Approved', 'Rejected'].includes(claim.status)
    return <article key={claim.id} className="rounded-2xl border border-ink/10 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-bold text-ink">{item?.title || 'Removed item'}</p><p className="mt-1 text-sm text-ink-muted">{item ? `${item.category} · ${item.type}` : 'Related item is no longer available'}</p></div><StatusBadge status={claim.status} /></div><dl className="mt-5 grid gap-4 border-y border-ink/10 py-4 text-sm sm:grid-cols-2"><ClaimDetail label="Claim ID" value={claim.id} /><ClaimDetail label="Claimant ID" value={claim.userId || 'Unknown'} /><ClaimDetail label="Privacy verification" value={claim.verified ? 'Verified' : claim.verificationStatus || 'Pending'} /><ClaimDetail label="Claim date" value={formatDate(claim.createdAt || claim.submittedAt)} /></dl>{claim.approvedAt && <p className="mt-4 text-xs text-ink-muted">Approved by {claim.approvedBy?.name || 'Admin'} on {formatDate(claim.approvedAt)}</p>}{claim.rejectedAt && <p className="mt-4 text-xs text-ink-muted">Rejected by {claim.rejectedBy?.name || 'Admin'} on {formatDate(claim.rejectedAt)}</p>}{!isFinal && <div className="mt-5 flex flex-wrap gap-3"><Button onClick={() => review(claim.id, 'approve')} disabled={!claim.verified}>Approve</Button><Button variant="outline" onClick={() => review(claim.id, 'reject')}>Reject</Button></div>}{!isFinal && !claim.verified && <p className="mt-3 text-xs font-medium text-ink-muted">Privacy verification is required before approval.</p>}</article>
  }) : <EmptyState title="No claims available" description="Claims submitted by users will appear here for review." />}</div></> }
function ClaimDetail({ label, value }) { return <div><dt className="text-xs font-bold uppercase tracking-wider text-ink-muted">{label}</dt><dd className="mt-1 break-all font-semibold text-ink">{value}</dd></div> }
function formatDate(value) { const date = new Date(value); return value && !Number.isNaN(date.getTime()) ? date.toLocaleString() : 'Not available' }
export function AdminRecoveryPage() {
  const [claims, setClaims] = useState(() => getClaims())
  const [passes, setPasses] = useState(() => getRecoveryPasses())
  const [items, setItems] = useState(() => getItems())
  const [message, setMessage] = useState('')
  const admin = getAdminSession()
  const approvedClaims = claims.filter((claim) => claim.status === 'Approved' && claim.verified)

  function refresh() { setClaims(getClaims()); setPasses(getRecoveryPasses()); setItems(getItems()) }
  function begin(claimId) { const result = startRecovery(claimId, admin); setMessage(result.error || (result.created ? 'Recovery Pass created. Item status is now Recovery Pending.' : 'An existing Recovery Pass is already linked to this claim.')); refresh() }
  return <><SectionHeading eyebrow="Administration" title="Recovery management" description="Start the online confirmation process for approved, privacy-verified claims." />{message && <p className="mt-6 rounded-xl bg-teal-pale p-4 text-sm font-medium text-teal-dark">{message}</p>}<div className="mt-6 grid gap-4">{approvedClaims.length ? approvedClaims.map((claim) => {
    const item = items.find((entry) => entry.id === claim.itemId)
    const pass = passes.find((entry) => entry.claimId === claim.id)
    return <article key={claim.id} className="rounded-2xl border border-ink/10 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-bold text-ink">{item?.title || 'Removed item'}</p><p className="mt-1 text-sm text-ink-muted">Claim {claim.id} · Claimant {claim.userId || 'Unknown'}</p></div>{pass && <StatusBadge status={pass.status} />}</div>{item ? <p className="mt-4 text-sm text-ink-muted">Item status: <span className="font-semibold text-ink">{item.status}</span></p> : <p className="mt-4 text-sm text-red-600">The related item is unavailable, so recovery cannot start.</p>}{pass ? <div className="mt-5 rounded-xl bg-paper p-4"><p className="text-xs font-bold uppercase tracking-wider text-teal">Recovery Pass</p><p className="mt-2 font-mono text-lg font-extrabold tracking-[0.18em] text-ink">{pass.code}</p><p className="mt-2 text-xs text-ink-muted">Pass ID: {pass.id}</p>{pass.status === 'Recovery Pending' && <p className="mt-4 text-sm font-medium text-ink-muted">Awaiting the claimant's online code confirmation.</p>}{pass.status === 'Recovered' && <p className="mt-4 text-sm font-semibold text-teal-dark">Confirmed online on {formatDate(pass.recoveredAt)}</p>}</div> : <Button className="mt-5" onClick={() => begin(claim.id)} disabled={!item}>Start Recovery</Button>}</article>
  }) : <EmptyState title="No approved claims ready for recovery" description="Claims must be approved and privacy-verified before a Recovery Pass can be created." />}</div></> }
