import { useState } from 'react'
import EmptyState from '../../components/common/EmptyState.jsx'
import SectionHeading from '../../components/common/SectionHeading.jsx'
import StatCard from '../../components/dashboard/StatCard.jsx'
import StatusBadge from '../../components/common/StatusBadge.jsx'
import { getClaims, getItems, updateItem } from '../../utils/storage.js'

const statuses = ['Searching', 'Found', 'Claim Pending', 'Recovered', 'Closed']
function ReportsTable({ items, onStatusChange }) { return <div className="overflow-x-auto rounded-2xl border border-ink/10 bg-white"><table className="min-w-[760px] w-full text-left text-sm"><thead className="border-b border-ink/10 bg-paper text-xs uppercase tracking-wider text-ink-muted"><tr>{['Item', 'Type', 'Category', 'Location', 'Date', 'Status', 'Action'].map((head) => <th key={head} className="px-4 py-3 font-bold">{head}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-b border-ink/5 last:border-0"><td className="px-4 py-4 font-bold text-ink">{item.title}</td><td className="px-4 py-4 text-ink-muted">{item.type}</td><td className="px-4 py-4 text-ink-muted">{item.category}</td><td className="px-4 py-4 text-ink-muted">{item.location}</td><td className="px-4 py-4 text-ink-muted">{item.date}</td><td className="px-4 py-4"><StatusBadge status={item.status} /></td><td className="px-4 py-4"><select value={item.status} onChange={(event) => onStatusChange(item.id, event.target.value)} className="rounded-lg border border-ink/15 bg-white px-2 py-1.5 text-xs font-semibold text-ink outline-none focus:border-teal">{statuses.map((status) => <option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div> }
export function AdminDashboardPage() { const [items, setItems] = useState(() => getItems()); const claims = getClaims(); const changeStatus = (id, status) => setItems((current) => current.map((item) => item.id === id ? updateItem(id, { status }) : item)); const stats = [['Total Reports', items.length, 'navy'], ['Lost Items', items.filter((item) => item.type === 'Lost').length, 'teal'], ['Found Items', items.filter((item) => item.type === 'Found').length, 'amber'], ['Potential Matches', Math.max(1, items.filter((item) => item.category === 'Wallets').length), 'teal'], ['Pending Claims', claims.filter((claim) => claim.status === 'Claim Pending').length, 'amber'], ['Recovered Items', items.filter((item) => item.status === 'Recovered').length, 'navy']]; return <><SectionHeading eyebrow="Demo administration" title="Recovery control center" description="Review community reports and keep the recovery process moving." /><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{stats.map(([label, value, accent]) => <StatCard key={label} label={label} value={value} accent={accent} />)}</div><h2 className="mt-10 text-xl font-extrabold text-ink">Reports</h2><div className="mt-4"><ReportsTable items={items} onStatusChange={changeStatus} /></div></> }
export function AdminReportsPage() { const [items, setItems] = useState(() => getItems()); const [query, setQuery] = useState(''); const filtered = items.filter((item) => `${item.title} ${item.location}`.toLowerCase().includes(query.toLowerCase())); const changeStatus = (id, status) => setItems((current) => current.map((item) => item.id === id ? updateItem(id, { status }) : item)); return <><SectionHeading eyebrow="Administration" title="Reports" description="Search and update the status of every report." /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search reports" className="mt-6 w-full max-w-sm rounded-xl border border-ink/15 bg-white px-4 py-3 text-sm outline-none focus:border-teal" /><div className="mt-5"><ReportsTable items={filtered} onStatusChange={changeStatus} /></div></> }
export function AdminClaimsPage() { const claims = getClaims(); const items = getItems(); return <><SectionHeading eyebrow="Administration" title="Claims" description="Review submitted ownership claims." /><div className="mt-6 grid gap-4">{claims.length ? claims.map((claim) => <article key={claim.id} className="rounded-2xl border border-ink/10 bg-white p-5 shadow-sm"><div className="flex justify-between gap-4"><div><p className="font-bold text-ink">{items.find((item) => item.id === claim.itemId)?.title || 'Item'}</p><p className="mt-1 text-sm text-ink-muted">Claimed by {claim.userName}</p></div><StatusBadge status={claim.status} /></div><p className="mt-3 text-xs text-ink-muted">Verification: {claim.verified ? 'Completed' : 'Pending'}</p></article>) : <EmptyState title="No claims submitted" description="Claims submitted by users will appear here." />}</div></> }
export function AdminRecoveryPage() { return <><SectionHeading eyebrow="Administration" title="Recovery management" description="Recovered reports will be visible here as the final handover step is completed." /><div className="mt-6"><EmptyState title="Recovery passes are issued after approval" description="For this frontend demo, changing an item to Recovered reflects the completed recovery state." /></div></> }
